### ISSUE TITLE
WeChat APIs availability is for organisations and individuals of China Only.

### ISSUE THREAD

**Issue by fatimarafiqui** [fossasia/eventyay-video#1]
For getting access to WeChat APIs an organisation or individual must be from China and have operator credentials etc of China itself for both a Subscription Account (free) or a Service Account. Without verification of mobile number and organisation one cannot seek the privilege.
@mariobehling @jig08 @Orbiter 

[WeChat Subscription Link](https://mp.weixin.qq.com/)

<img width="1247" alt="screen shot 2016-12-04 at 15 14 22" src="https://cloud.githubusercontent.com/assets/13470643/20865313/7db4787e-ba34-11e6-8fd7-127c9470c061.png">

**Comment by mariobehling** [comment]
@fatimarafiqui Maybe there is a test account option somewhere. We can also let someone from China take up this issue. Thanks.

**Comment by fatimarafiqui** [comment]
@mariobehling No, I checked it few times, there is no test account option available. Also If someone from China can help me get the credentials, I can do it.

**Comment by mariobehling** [comment]
@fatimarafiqui Ok, thanks. Not sure, who could help. Maybe @DengYiping

**Comment by DengYiping** [comment]
Yes, I can help. @fatimarafiqui  I am currently in mainland China.

**Comment by fatimarafiqui** [comment]
Hey @DengYiping, This is the [WeChat Subscription Link](https://mp.weixin.qq.com). Please sign up with your credentials and give me the details for login. In case you want to convert the page from Chinese to English you can use Google Chrome for the same. I tried using other browsers but it did not work out for me. 
That would be great help. Thanks!
