### ISSUE TITLE
Implement translation/interpretation system 

### ISSUE THREAD

**Issue by untari** [fossasia/eventyay-video#103]
Initial tasks for implementing a translation/interpretation system. This list is likely to grow as we progress.

- [x] Investigate streaming configuration options
- [x] Enable YouTube video as a streaming source
- [x] Implement a language selection dropdown menu
- [x] Pre-load audio on language button selection
- [ ] Configure translations button functionality

The functionality works in the way that the video source stays always the same no matter what language is used. But: When the user clicks on another language the audio source changes.

**Comment by mariobehling** [comment]
Duplicate of https://github.com/fossasia/eventyay-video/issues/113
