### ISSUE TITLE
Creating a world results in invalid token message

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-video#124]
Creating an online world via "admin access," results in "invalid token" error.

![photo_6316353032517958845_y](https://github.com/fossasia/eventyay-video/assets/1583873/6155e301-a369-4ff2-b84e-7b0bcbe0f1ad)

**Comment by odkhang** [comment]
As discussed on Telegram, root cause is the secret key of sample data different with secret key of created world, after update the domain of sample world to video-dev.eventyay.com, it working as expected.

**Comment by untari** [comment]
@odkhang thanks for looking into this!
