### ISSUE TITLE
Enhance Chat Mentions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-video#138]
**Objective:**
Let's implement @username mentions in the chat to make our communication more interactive and user-friendly.

**Details:**
Currently, unique usernames aren't available, so we'll save @USER_ID and resolve the display name when rendering the chat messages.

**Frontend Tasks:**
- [ ] Add the ability to create mentions while composing messages in Quill (using [quill-mention](https://github.com/quill-mention/quill-mention) as a base, but it will need some enhancements for better rendering).
  - [ ] Display avatars in the dropdown for easy identification
  - [ ] Implement a page blocker to improve user interaction during mention selection
- [ ] Ensure @ mentions are correctly rendered in text messages.
  - [ ] Make mentions clickable to open the user card
- [ ] Notify users when their mentions might not trigger a notification, especially if the mentioned user is not in the channel

**Backend Tasks:**
- [ ] Parse @ mentions and send out notifications
- [ ] Ensure unread messages are stored when users are offline
- [ ] Include message content in notifications

**Why This Matters:**
By completing these tasks, we can significantly enhance the chat experience for everyone. Your contributions will help make our platform more engaging and responsive. Let's collaborate and make this feature awesome!

**Comment by odkhang** [comment]
hi @mariobehling 
Could you please confirm the requirements for how @ mentions should behave? Specifically:

1. Should the user card be displayed only when an @ mention is rendered in the text message, or
2. Should the user card also be displayed when the @ mention is clicked in the chat box?
