### ISSUE TITLE
Fix tab links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-video#153]
Tab links are not always consistent and change if a new tab gets added in-between existing tabs.

**Comment by NageshMandal** [comment]
could you please assign me this issue i want to work on it

**Comment by mariobehling** [comment]
We dont assign issues to new contributors. If you are interested in solving an issue please go ahead and make a pull request.

**Comment by NageshMandal** [comment]
okey.... thankyou sir @mariobehling
