### ISSUE TITLE
Add UI translations for Arabic, French, Spanish, Ukrainian, Russian

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-video#180]
Add UI translations for Arabic, French, Spanish, Ukrainian, Russian. Use the option to translate UI with automatic translation tools. 

Use choice of language of users coming from eventyay-tickets or -talk.

![Screenshot from 2024-07-28 16-26-43](https://github.com/user-attachments/assets/2c3037fa-2ef5-4388-b4cd-3d6c0d54e75f)

**Comment by Dishebh** [comment]
I think this can be closed as well
