### ISSUE TITLE
Link to session on speaker page not loading

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-video#185]
When visiting the speaker's page there is a section with the session information. Clicking this session link does not load the session page.

![Screenshot from 2024-07-30 16-46-46](https://github.com/user-attachments/assets/bf93e786-6124-485f-8aec-52b7d5501642)

**Comment by Dishebh** [comment]
Hey @mariobehling, can you help me with how to setup this project locally? I see an app-wise readme, for example, readme inside the webapp dir. But the file is 3 years old, and the setup instructions there don't apply much, or doesn't work for me now.

**Comment by Dishebh** [comment]
Hey @mariobehling , clicking the session link does open the session information. Can you check if the bug still exists?
